### ISSUE TITLE
千葉県版へのリンクを公式のものに変更する

### ISSUE THREAD

**Issue by yukiyalien** [hidehiro98/stopcovid19japan#4]
はじめまして。GitHub初心者であるため、このIssueになにか問題や失礼がありましたらごめんなさい:bow:

千葉県版のCOVID-19対策サイトですが、既にこのサイトに記載されている
- https://chiba-covid19.mypl.net/ (by まいぷれ)

に加えて、千葉県が公式でリンクしている
- https://covid19.civictech.chiba.jp/ (by CivicTechZenChiba)

も存在しています。CivicTechZenChibaの方は[県の公式HP](https://www.pref.chiba.lg.jp/)からもリンクされており公式に認められたものなので、貴サイト上の千葉県版へのリンクをこちらに変更するか、あるいは2つ併記するかをした方が良いのではないでしょうか？

**Comment by hidehiro98** [comment]
ご指摘ありがとうございます！
確認したところ、データの更新頻度もご指摘いただいたリンクの方がされているため、変更させていただきました。
ありがとうございました！

**Comment by yukiyalien** [comment]
ありがとうございます🙇🙇🙇🙇✨✨✨
